theme = "tokyonight_storm"

[editor]
line-number = "relative"
mouse = false
shell  = ["zsh", "-c"]
bufferline = "always"
jump-label-alphabet = "fjdklavmceiruwotybns;"
end-of-line-diagnostics = "hint"
cursorline = true

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
right = [ "position", "position-percentage", "total-line-numbers", "selections"]
center = [ "file-name", "separator", "version-control" ]
left = [ "mode", "spinner", "diagnostics" ]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
separator = " │ "

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
# Navigation
C-d = ["half_page_down", "goto_window_center"]
C-u = ["half_page_up", "goto_window_center"]
ret = "goto_word"
C-j = ['ensure_selections_forward', 'extend_to_line_bounds', 'extend_char_right', 'extend_char_left', 'delete_selection', 'add_newline_below', 'move_line_down', 'replace_with_yanked']
C-k = ['ensure_selections_forward', 'extend_to_line_bounds', 'extend_char_right', 'extend_char_left', 'delete_selection', 'move_line_up', 'add_newline_above', 'move_line_up', 'replace_with_yanked']

# Buffer & Window Management
C-q = ":buffer-close!"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"]
tab = "buffer_picker"
# File explorer with yazi integration
S-tab = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-h21a434",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":redraw",
]
C-t = ":toggle file-picker.git-ignore"

# Editing Commands
d = "delete_selection_noyank"
c = "change_selection_noyank"
X = "extend_line_above"
S = "@ /%p <C-r>% %n "  # Open string search on current buffer

# Commenting & Code Manipulation
C-c = ["toggle_comments", "move_line_down"]

# Escape & Selection Handling
esc = ["collapse_selection", "keep_primary_selection"]

# Saving
C-s = ["normal_mode", ":w"]

[keys.normal.space]
# Open HTML preview of markdown content in a browser
# Once the following gets merged, a custom label could be used
# https://github.com/helix-editor/helix/pull/3958
o = ":lsp-workspace-command open-preview"

[keys.select]
# Selection Navigation
X = "select_line_above"
x = "select_line_below"

# Editing Commands
d = "delete_selection_noyank"
c = "change_selection_noyank"

# Saving
C-s = ["normal_mode", ":w"]

[keys.insert]
# Saving
C-s = ["normal_mode", ":w"]
# Esc replacement
j = { k = "normal_mode" }
