theme = "tokyo_night_storm"

[editor]
line-number = "relative"
mouse = false
shell  = ["zsh", "-c"]
bufferline = "always"
jump-label-alphabet = "fjdklavmceiruwotybns;"
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
right = [ "position", "position-percentage", "total-line-numbers", "selections"]
center = [ "file-name", "separator", "version-control" ]
left = [ "mode", "spinner", "diagnostics" ]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
separator = " │ "

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
# Navigation
"J" = "@15zj" # Scroll down
"K" = "@15zk" # Scroll up
C-d = ["half_page_down", "goto_window_center"]
C-u = ["half_page_up", "goto_window_center"]
ret = "goto_word"

# Buffer & Window Management
C-q = ":buffer-close!"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload-all"]
tab = "buffer_picker"
S-tab = "file_picker"
C-t = ":toggle file-picker.git-ignore"

# Editing Commands
d = "delete_selection_noyank"
c = "change_selection_noyank"
X = "extend_line_above"
S = "@ /%p <C-r>% %n "  # Open string search on current buffer

# Commenting & Code Manipulation
C-c = ["toggle_comments", "move_line_down"]

# Escape & Selection Handling
esc = ["collapse_selection", "keep_primary_selection"]

# Saving
C-s = ["normal_mode", ":w"]

[keys.select]
# Selection Navigation
X = "select_line_above"
x = "select_line_below"

# Editing Commands
d = "delete_selection_noyank"
c = "change_selection_noyank"

# Saving
C-s = ["normal_mode", ":w"]

[keys.insert]
# Saving
C-s = ["normal_mode", ":w"]
