theme = "github_dark_dimmed"

[editor]
line-number = "relative"
mouse = false
shell  = ["zsh", "-c"]
bufferline = "always"

# [editor.whitespace]
# render = "all"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-d = ["half_page_down", "goto_window_center"]
C-u = ["half_page_up", "goto_window_center"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

# [keys.normal.space.space]
# f = "file_browser"
